### ISSUE TITLE
Importador.cs is Missing

### ISSUE THREAD

**Issue by lucaslra** [RARomano/FileManager#2]
Hi,

I just cloned the project for a first look but there is some missing files in the Solution.
The missing files are Importador.cs, Importador.Designer.cs, Importador.resx

I guess you've started working in the Import part of the tool, but forgot to commit this changes.

![missingfiles](https://cloud.githubusercontent.com/assets/2528972/7446741/ba374344-f1b8-11e4-8fe5-e76b942b76ba.PNG)

**Comment by RARomano** [comment]
Hi Lucas,

Thank you for downloading the solution and reporting the bug. 

I've added the missing files in the solution in my last commit https://github.com/RARomano/FileManager/commit/adf5ae7cbd913dd8cc5268734bd0cc861befcfa4
